### PR TITLE
Changes for functional interoperability with other Promise implementations

### PR DESCRIPTION
**Pull request by techno-express**

### CODE REVIEW

**Comment by evert** [comment]
One of my goals with the sabre/event package was to create a set of event-related patterns in a very simple way. Removing all the cruft basically.

I'm a little worried that introducing these changes causes this package to no longer live up to that goal. If you want the kitchen sink, why not just use Guzzle's?

If interop is the main goal, is it possible to create interop by creating a separate interop package and subclass the Promise class?

**Comment by techno-express** [comment]
I'm not using Guzzle, for I was creating my own package to learn how async php should work. I hit a wall, it work to an certain point and since it's an combination of everybody JavaScript implementation specs, it should work regardless of the internal implementation routines. 

The results of basic same call structure should get the same answers. Your current implementations claiming %100 doesn't, the tests indicate that's the case without modifying.  I discovered the reason why my own package wasn't working by working on what you have here. So you could say the **interop** idea originated here. I now understand why the few skipped tests here fails, working on solution.

So i am giving it back. I will be introducing the the same to React and Guzzle cause there too, they don't interact without some small changes. 

I don't see where simplicity is removed, maybe the terminology used should change. 

Also i am following everything async php related, making comments for reference for future use.

**Comment by evert** [comment]
Hi @techno-express ,

> The results of basic same call structure should get the same answers. Your current implementations claiming %100 doesn't,

I'm not entirely sure where that claim was made, or what this refers to exactly, But if you're trying to fix an implementation problem I'm having a hard time reading through your changes and pinpointing it. Part of the problem is that you're fixing a bunch of different things at the same, while they would probably have been better as separate smaller pull requests.

Anyway, the two major things I see are:

1. Adding cancel support. I'm not necessarily against this idea, but I would rather see a `CancelablePromise` than to integrate it into the core object. I don't think it's needed to tack this onto the existing class.
2. Support for different loop implementations. It's unclear what those are, as everything is done via duck-typing.

I don't think changing the promise and ducktyping on different loop objects was the right extension point. What should have been done instead is (perhaps) subclassing `Sabre\Event\Loop` with a new implementation that delegates it's functions to another implementation (such as guzzle's or reactphp).

Such 'bridges' for different loop implementations should be done in separate composer packages that have hard dependencies on `Sabre\Event` and the package you're integrating with.

Are those the main things, or are there other details I've missed? If so, can you share a simple example of what this package currently does incorrectly?

**Comment by evert** [comment]
Hi @techno-express 

I see you're still working on this. I'm assuming this is now just your private branch and commits just make their way into this PR and my notification list.

I'm closing this PR for now. If you have small, isolated contributions that follow the coding standards, I would suggest you open individual PR's.

**Comment by techno-express** [comment]
How do you figure it's my private branch?
From your first response it seems to me this library is your private repo in the open.

Why would i put in more PR? It's about your users/community, not you. 
I am showing the issues, and since nobody has chimed in, you must have no users. I guess it has limited use case as implemented. I normally post no issues anywhere, unless i can't fix myself, and that's rare.

This library might as well be considered unmaintained abandoned.

I guess i will be extracting the promise part under it's own repo library from this commit. Maybe you will see that as not private.

You, the developer, fall into an category that necessitate an flaming like reply, which I been avoiding from the beginning.
 
I was surprise to see the PR open for so long. I find some project's keep PR open for years, just for there community to inspect.

**Comment by evert** [comment]
Hi,

I appreciate the effort but the quality of contributions are just not up to par. And you're right I don't spend a lot of time on this project. I don't have the time to take your changes and extract what you're trying to accomplish and clean it up. Sorry about that. Small islolated changes are just easier to deal with . Your comment didn't sound insulting to me, I understand why you might be frustrated.

**Pull request closed without merging**
