### PR TITLE
Exclude more files in production

### PR DESCRIPTION
**Pull request by vinkla**
This pull request excludes even more files which we don't need in production.

https://www.reddit.com/r/PHP/comments/2jzp6k/i_dont_need_your_tests_in_my_production/

### CODE REVIEW

**Comment by staabm** [comment]
Thx

**Comment by DominikTo** [comment]
Should we really do this?
See discussion here: sabre-io/uri#29

**Comment by staabm** [comment]
IMO deleting things like `tests/` folder is very valuable, since those can contain security vulnerabilities and produce unnecessary long deployment cycles and download times.

since all those information is still present while development I dont see a reason to keep them.

I dont have a strong opinion on this few files which were deleted with this particular PR though.

@DominikTo  is it a particular file which you want not to be git-ignored, or is your point more generell?

**Comment by vinkla** [comment]
One thing that is almost never discussed is moving data and what that costs the environment. A few kilobytes downloaded once is nothing but if you put it all together it becomes quite much.

> Therefore you need 2.04 kg of coal to download 1 mb of data if your internet speed is 1mb per minute - [Ankit Kumar](https://www.quora.com/How-much-coal-has-to-be-burnt-to-download-1MB-of-data-from-the-Internet/answer/Ankit-Kumar-364?share=1)

**Comment by DominikTo** [comment]
My point is more general. As mentioned in sabre-io/uri#29 - I don't have a strong opinion on this, but there seem to be legitimate drawbacks and little to gain.

See e.g.:
* https://github.com/symfony/symfony/issues/6605#issue-9740742
* https://github.com/symfony/symfony/issues/6605#issuecomment-11962088

**Comment by staabm** [comment]
@DominikTo  in my personal experience I had problem with long lasting deployments and security vulnerabilities because of test-mocks therefore I have good reasons (or at least have examples from personal experience) to leave thoses things out.

**Pull request merged**
