### PR TITLE
chore: add PHP 8.4 to CI

### PR DESCRIPTION
**Pull request by phil-davis**
Let's see if GitHub knows about PHP 8.4 alpha yet.

### CODE REVIEW

**Comment by staabm** [comment]
I would be fine with skipping cs-fixer for 8.4 for now

**Comment by staabm** [comment]
(or maybe we just need to update cs-fixer)

**Comment by phil-davis** [comment]
The deprecation messages are all for vendor packages. And some are inside vendor, phpstan, vendor again - dependencies of phpstan itself.

So various dependencies need to be "fixed" first anyway.

**Comment by phil-davis** [comment]
See PR #126 for the 5.1 branch. We can get that approved and merged first, then I will see what finally should be done here in master.

**Comment by phil-davis** [comment]
See #136

**Pull request closed without merging**
